#!/usr/bin/env python3
"""One picture in every theme's shades, as a sheet to look at.

    python3 tools/image_themes.py somewhere/photo.jpg          # into build/image-themes
    python3 tools/image_themes.py photo.jpg --levels 4
    python3 tools/image_themes.py photo.jpg --out /tmp/look

The badge takes the indices the host dithered and writes the theme's shades into the
image's colour table. This does that second half on the host, so whether a ramp is any
good becomes something to look at and not a set of numbers. Every theme at once is the
only way to see that one has gone muddy.

Each tile is drawn on that theme's background with its ink beside it. A picture is only
ever seen on a page, and shades that look fine on white can disappear on the page they
are going on.

"""

import argparse
import io
import pathlib
import struct
import sys
import zlib

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent / "src"))

from statsbadge import derive, imaging, layout  # noqa: E402

# The tile, and the room around it. A picture is shown at the size the badge draws it, since
# what a dither looks like is a question about pixels and scaling it answers a different one.
PAD = 10
LABEL_H = 14
COLUMNS = 4


def sheet(indices, width, height, themes, levels, tint):
    """Every theme's take on one picture, as an RGB raster and its size."""
    tile_w, tile_h = width + PAD * 2, height + PAD * 2 + LABEL_H
    rows = -(-len(themes) // COLUMNS)
    sheet_w, sheet_h = tile_w * COLUMNS, tile_h * rows
    raster = bytearray(sheet_w * sheet_h * 3)

    for at, name in enumerate(themes):
        palette = layout.palette_for(name, tint)
        shades = [tuple(rgb) for rgb in palette["image"][str(levels)]]
        background, ink = tuple(palette["bg"]), tuple(palette["ink"])
        left, top = (at % COLUMNS) * tile_w, (at // COLUMNS) * tile_h

        for y in range(tile_h):
            for x in range(tile_w):
                at_pixel = ((top + y) * sheet_w + left + x) * 3
                raster[at_pixel:at_pixel + 3] = bytes(background)
        for y in range(height):
            for x in range(width):
                at_pixel = ((top + PAD + y) * sheet_w + left + PAD + x) * 3
                raster[at_pixel:at_pixel + 3] = bytes(shades[indices[y * width + x]])
        # The shades themselves under the picture, as a strip. What a photograph looks
        # like and what the ramp actually is are different questions.
        strip = top + PAD + height + 3
        for step, shade in enumerate(shades):
            wide = width // len(shades)
            for y in range(6):
                for x in range(wide):
                    at_pixel = ((strip + y) * sheet_w + left + PAD + step * wide + x) * 3
                    raster[at_pixel:at_pixel + 3] = bytes(shade)
        # A rule in the ink, so a tile whose picture has vanished into its page still shows
        # where it was.
        for x in range(width):
            at_pixel = ((strip + 8) * sheet_w + left + PAD + x) * 3
            raster[at_pixel:at_pixel + 3] = bytes(ink)
    return bytes(raster), sheet_w, sheet_h


def test_card():
    """A picture that asks the ramp the questions worth asking, as PNG bytes.

    The default, so looking at what a theme does to a picture never means helping
    yourself to somebody's holiday snap off a public timeline.

    It carries the three things a four-level dither can get wrong. A smooth sweep is where
    banding and the Bayer texture show. Flat patches at each level are where a ramp with
    two shades too close together stops having four. Edges at several angles are what the
    crop scores and what a dither can turn to mush.
    """
    from PIL import Image, ImageDraw

    width, height = 640, 480
    card = Image.new("L", (width, height), 0)
    draw = ImageDraw.Draw(card)
    for x in range(width):
        draw.line([(x, 0), (x, height // 3)], fill=int(x * 255 / (width - 1)))
    step = width // 8
    for band in range(8):
        draw.rectangle([band * step, height // 3, (band + 1) * step - 1, height // 2],
                       fill=band * 255 // 7)
    # Something to look at, off centre so the crop has a decision to make.
    draw.ellipse([360, 250, 600, 460], fill=230, outline=20, width=6)
    draw.ellipse([410, 300, 550, 410], fill=40)
    for at in range(0, 340, 26):
        draw.line([(at, height), (at + 120, height // 2)], fill=200, width=3)
    draw.rectangle([30, 300, 180, 400], fill=120, outline=255, width=4)

    raw = io.BytesIO()
    card.save(raw, format="PNG")
    return raw.getvalue()


def write_cards(data):
    """A thumbnail per preset and a palette per theme, for the badge-side probe to import.

    Generated rather than committed: a thumbnail is bytes, and bytes do not belong in a
    source file. Written into build/, which the badge sees over the mount.
    """
    import base64
    import json

    lines = ["# Generated by tools/image_themes.py --cards, for tools/notify_probe.py\n"]
    for preset in sorted(imaging.LEVELS):
        png = imaging.thumbnail(data, preset, "landscape")
        lines.append(f'{preset.upper()} = "{base64.b64encode(png).decode()}"\n')
    tint = layout.DEFAULT_CONFIG["tint"]
    # A few themes rather than all twenty: what the probe is checking is that a palette
    # reaches an image's table, and three of them show that as well as every one would.
    wanted = ("dark", "luminescence", "mono")
    lines.append("PALETTES = "
                 + json.dumps({name: layout.palette_for(name, tint) for name in wanted})
                 + "\n")
    path = pathlib.Path("build/probe_pictures.py")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("".join(lines))
    print(f"{path}  {path.stat().st_size} bytes")


def write_png(path, raster, width, height):
    rows = b"".join(b"\x00" + raster[y * width * 3:(y + 1) * width * 3]
                    for y in range(height))

    def chunk(tag, body):
        block = tag + body
        return (struct.pack(">I", len(body)) + block
                + struct.pack(">I", zlib.crc32(block) & 0xFFFFFFFF))

    path.write_bytes(b"\x89PNG\r\n\x1a\n"
                     + chunk(b"IHDR", struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0))
                     + chunk(b"IDAT", zlib.compress(rows, 9))
                     + chunk(b"IEND", b""))


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("picture", nargs="?",
                        help="any image Pillow can read, or a test card if left out")
    parser.add_argument("--out", default="build/image-themes")
    parser.add_argument("--levels", type=int, choices=sorted(imaging.LEVELS.values()),
                        default=None, help="both, unless one is named")
    parser.add_argument("--orientation", default="landscape",
                        choices=("landscape", "portrait"))
    parser.add_argument("--cards", action="store_true",
                        help="write build/probe_pictures.py for tools/notify_probe.py "
                             "instead of a sheet")
    args = parser.parse_args(argv)

    data = pathlib.Path(args.picture).read_bytes() if args.picture else test_card()
    if args.cards:
        write_cards(data)
        return
    out = pathlib.Path(args.out)
    out.mkdir(parents=True, exist_ok=True)

    from PIL import Image

    wanted = [args.levels] if args.levels else sorted(set(imaging.LEVELS.values()))
    themes = list(layout.THEMES)
    tint = layout.DEFAULT_CONFIG["tint"]
    for levels in wanted:
        preset = next(name for name, count in imaging.LEVELS.items() if count == levels)
        png = imaging.thumbnail(data, preset, args.orientation)
        indexed = Image.open(io.BytesIO(png))
        width, height = indexed.size
        raster, sheet_w, sheet_h = sheet(indexed.tobytes(), width, height, themes,
                                         levels, tint)
        path = out / f"themes-{preset}-{args.orientation}-{levels}.png"
        write_png(path, raster, sheet_w, sheet_h)
        print(f"{path}  {len(themes)} themes at {width}x{height}, {levels} shades")

    # What each theme is actually asking for: a sheet shows which looks wrong and this
    # says why: a picture is as colourful as the theme's own accent is.
    print()
    print(f"{'theme':22} {'accent share':>13} {'strongest shade':>16}")
    for name in themes:
        palette = layout.palette_for(name, tint)
        light, chroma, hue = derive.oklch(tuple(palette["accent"]))
        limit = derive.max_chroma(light, hue)
        share = (chroma / limit) if limit else 0.0
        loudest = max(derive.oklch(tuple(rgb))[1]
                      for rgb in palette["image"][str(wanted[-1])])
        print(f"  {name:20} {share:13.2f} {loudest:16.3f}")


if __name__ == "__main__":
    raise SystemExit(main())
